-- ============================================================================
-- KSarees — seed data
--
-- INTENTIONALLY EMPTY. The catalogue ships with NO seed/mock products so the
-- live store starts clean. Add real inventory through the admin panel
-- (/admin/products) against a configured Supabase project, or insert your own
-- rows here. All prices are authored in AUD (the canonical base currency).
--
-- To wipe existing catalogue rows without touching schema, run wipe.sql.
-- ============================================================================
